import { originColors } from '@mazaq/tokens';
import { img } from './images';
import { priceTable } from './markets';
import type { BeanDetails, CustomizationKey, MenuItem } from './types';

/*
 * Menu data. Prices are EGP shelf prices with 14% VAT included; other currencies
 * are generated from markets.ts and are PLACEHOLDERS until the client confirms them.
 * Nutrition values are working values — confirm with a nutritionist before launch.
 */

const HOT: CustomizationKey[] = ['size', 'milk', 'shots', 'sweetness', 'syrup', 'temperature'];
const ICED: CustomizationKey[] = ['size', 'milk', 'shots', 'sweetness', 'ice', 'syrup'];
const BLACK_HOT: CustomizationKey[] = ['size', 'shots', 'sweetness', 'temperature'];
const BLACK_ICED: CustomizationKey[] = ['size', 'shots', 'sweetness', 'ice'];

type DrinkInput = Omit<MenuItem, 'id' | 'basePrice' | 'customizable' | 'category' | 'kind'> & {
  price: number;
};

const hot = ({ price, ...d }: DrinkInput): MenuItem => ({
  ...d,
  id: d.slug,
  category: 'hot-coffee',
  kind: 'hot',
  basePrice: priceTable(price),
  customizable: d.customizations.length > 0,
});

const iced = ({ price, ...d }: DrinkInput): MenuItem => ({
  ...d,
  id: d.slug,
  category: 'iced-coffee',
  kind: 'iced',
  basePrice: priceTable(price),
  customizable: d.customizations.length > 0,
});

export const hotCoffee: MenuItem[] = [
  hot({
    slug: 'saffron-honey-latte',
    name: { en: 'Saffron Honey Latte', ar: 'لاتيه الزعفران والعسل' },
    description: {
      en: 'House Espresso and steamed milk infused with Spanish saffron, sweetened with Sidr honey.',
      ar: 'إسبريسو البيت وحليب مبخّر منقوع بالزعفران الإسباني ومحلّى بعسل السدر.',
    },
    kcal: 210,
    caffeineMg: 150,
    allergens: ['milk'],
    tags: ['seasonal', 'dairy-free-option', 'decaf-available'],
    price: 155,
    customizations: HOT,
    defaultShots: 2,
    image: img('latte-art'),
    art: { tone: '#E3A62B', ink: '#8A5A2B' },
    pairsWith: 'overnight-oats-dates-tahini',
  }),
  hot({
    slug: 'espresso',
    name: { en: 'Espresso', ar: 'إسبريسو' },
    description: {
      en: 'A double shot of House Espresso. Caramel, cocoa and a little red fruit.',
      ar: 'شوت دبل من إسبريسو البيت. كراميل وكاكاو ولمسة فاكهة حمراء.',
    },
    kcal: 5,
    caffeineMg: 130,
    allergens: [],
    tags: ['vegan', 'no-added-sugar', 'decaf-available'],
    price: 70,
    customizations: ['shots', 'sweetness'],
    defaultShots: 2,
    image: img('espresso'),
    art: { tone: '#F1E7D8', ink: '#3A2418' },
    pairsWith: 'egg-white-spinach-omelette',
  }),
  hot({
    slug: 'americano',
    name: { en: 'Americano', ar: 'أمريكانو' },
    description: {
      en: 'House Espresso lengthened with hot water. Clean and easy.',
      ar: 'إسبريسو البيت مع ماء ساخن. خفيف ونظيف.',
    },
    kcal: 10,
    caffeineMg: 150,
    allergens: [],
    tags: ['vegan', 'no-added-sugar', 'decaf-available'],
    price: 90,
    customizations: BLACK_HOT,
    defaultShots: 2,
    image: img('espresso-glass'),
    art: { tone: '#F1E7D8', ink: '#3A2418' },
    pairsWith: 'avocado-egg-sourdough',
  }),
  hot({
    slug: 'flat-white',
    name: { en: 'Flat White', ar: 'فلات وايت' },
    description: {
      en: 'Two ristretto shots under a thin layer of velvety milk.',
      ar: 'شوتان ريستريتو تحت طبقة رقيقة من الحليب المخملي.',
    },
    kcal: 120,
    caffeineMg: 130,
    allergens: ['milk'],
    tags: ['dairy-free-option', 'decaf-available', 'no-added-sugar'],
    price: 110,
    customizations: HOT,
    defaultShots: 2,
    image: img('flat-white'),
    art: { tone: '#F1E7D8', ink: '#6B4A33' },
    pairsWith: 'avocado-egg-sourdough',
  }),
  hot({
    slug: 'cappuccino',
    name: { en: 'Cappuccino', ar: 'كابتشينو' },
    description: {
      en: 'Espresso with equal parts steamed milk and deep, airy foam.',
      ar: 'إسبريسو مع حليب مبخّر ورغوة كثيفة بالتساوي.',
    },
    kcal: 130,
    caffeineMg: 150,
    allergens: ['milk'],
    tags: ['dairy-free-option', 'decaf-available', 'no-added-sugar'],
    price: 105,
    customizations: HOT,
    defaultShots: 2,
    image: img('cappuccino'),
    art: { tone: '#F1E7D8', ink: '#6B4A33' },
    pairsWith: 'greek-yogurt-berry-parfait',
  }),
  hot({
    slug: 'caffe-latte',
    name: { en: 'Caffè Latte', ar: 'كافيه لاتيه' },
    description: {
      en: 'Espresso and plenty of steamed milk with a light cap of foam.',
      ar: 'إسبريسو مع كمية وافرة من الحليب المبخّر وطبقة رغوة خفيفة.',
    },
    kcal: 190,
    caffeineMg: 150,
    allergens: ['milk'],
    tags: ['dairy-free-option', 'decaf-available', 'no-added-sugar'],
    price: 110,
    customizations: HOT,
    defaultShots: 2,
    image: img('latte-art'),
    art: { tone: '#F1E7D8', ink: '#8B6245' },
    pairsWith: 'greek-yogurt-berry-parfait',
  }),
  hot({
    slug: 'spanish-latte',
    name: { en: 'Spanish Latte', ar: 'سبانيش لاتيه' },
    description: {
      en: 'Double espresso, steamed milk and a ribbon of condensed milk.',
      ar: 'إسبريسو دبل مع حليب مبخّر وخيط من الحليب المكثف.',
    },
    kcal: 260,
    caffeineMg: 150,
    allergens: ['milk'],
    tags: ['bestseller', 'decaf-available'],
    price: 135,
    customizations: HOT,
    defaultShots: 2,
    image: img('spanish-latte'),
    art: { tone: '#F1E7D8', ink: '#7A5236' },
    pairsWith: 'halloumi-zaatar-wrap',
  }),
  hot({
    slug: 'mocha',
    name: { en: 'Mocha', ar: 'موكا' },
    description: {
      en: 'Espresso, dark chocolate and steamed milk.',
      ar: 'إسبريسو وشوكولاتة داكنة وحليب مبخّر.',
    },
    kcal: 290,
    caffeineMg: 155,
    allergens: ['milk', 'soy'],
    tags: ['dairy-free-option', 'decaf-available'],
    price: 140,
    customizations: HOT,
    defaultShots: 2,
    image: img('cappuccino'),
    art: { tone: '#F1E7D8', ink: '#4A2A1C' },
    pairsWith: 'greek-yogurt-berry-parfait',
  }),
  hot({
    slug: 'turkish-coffee',
    name: { en: 'Turkish Coffee', ar: 'قهوة تركي' },
    description: {
      en: 'Mazaq Turkish Blend brewed slowly in a cezve. Plain or with cardamom.',
      ar: 'بن مذاق التركي يُحضَّر على مهل في الكنكة. سادة أو بالحبهان.',
    },
    kcal: 10,
    caffeineMg: 60,
    allergens: [],
    tags: ['turkish', 'vegan', 'no-added-sugar'],
    price: 75,
    customizations: ['cardamom', 'sweetness'],
    image: img('turkish-coffee'),
    art: { tone: '#F1E7D8', ink: '#3A2418' },
    pairsWith: 'green-shakshuka',
  }),
];

export const icedCoffee: MenuItem[] = [
  iced({
    slug: 'iced-spanish-latte',
    name: { en: 'Iced Spanish Latte', ar: 'آيس سبانيش لاتيه' },
    description: {
      en: 'Double House Espresso over cold milk, sweetened with condensed milk.',
      ar: 'إسبريسو البيت دبل على حليب بارد ومحلّى بالحليب المكثف.',
    },
    kcal: 240,
    caffeineMg: 150,
    allergens: ['milk'],
    tags: ['bestseller', 'decaf-available'],
    price: 145,
    customizations: ICED,
    defaultShots: 2,
    image: img('iced-latte-pour'),
    art: { tone: '#D8E6E3', ink: '#7A5236' },
    pairsWith: 'avocado-egg-sourdough',
  }),
  iced({
    slug: 'cold-brew',
    name: { en: 'Cold Brew', ar: 'كولد برو' },
    description: {
      en: 'Brazil and Colombia steeped for 18 hours. Smooth, low acid.',
      ar: 'بن برازيلي وكولومبي منقوع ١٨ ساعة. ناعم وقليل الحموضة.',
    },
    kcal: 5,
    caffeineMg: 200,
    allergens: [],
    tags: ['vegan', 'no-added-sugar'],
    price: 120,
    customizations: ['size', 'sweetness', 'ice'],
    image: img('cold-brew'),
    art: { tone: '#DCE3EC', ink: '#2E1F16' },
    pairsWith: 'acai-bowl',
  }),
  iced({
    slug: 'date-frappe',
    name: { en: 'Date Frappé', ar: 'فرابيه التمر' },
    description: {
      en: 'Medjool dates, double espresso and oat milk, blended with ice.',
      ar: 'تمر مجدول وإسبريسو دبل وحليب شوفان، مخفوقة بالثلج.',
    },
    kcal: 310,
    caffeineMg: 130,
    allergens: [],
    tags: ['seasonal', 'vegan', 'no-added-sugar'],
    price: 165,
    customizations: ['size', 'shots', 'sweetness', 'ice'],
    defaultShots: 2,
    image: img('date-frappe'),
    art: { tone: '#F3E6CF', ink: '#8A5A2B' },
    pairsWith: 'overnight-oats-dates-tahini',
  }),
  iced({
    slug: 'espresso-tonic',
    name: { en: 'Espresso Tonic', ar: 'إسبريسو تونك' },
    description: {
      en: 'Ethiopia espresso over tonic water and a twist of orange.',
      ar: 'إسبريسو إثيوبي على مياه التونك مع قشر البرتقال.',
    },
    kcal: 90,
    caffeineMg: 130,
    allergens: [],
    tags: ['vegan'],
    price: 130,
    customizations: ['ice'],
    image: img('espresso-tonic'),
    art: { tone: '#E6EEDC', ink: '#4A2F20' },
    pairsWith: 'acai-bowl',
  }),
  iced({
    slug: 'iced-americano',
    name: { en: 'Iced Americano', ar: 'آيس أمريكانو' },
    description: {
      en: 'House Espresso over cold water and ice.',
      ar: 'إسبريسو البيت على ماء بارد وثلج.',
    },
    kcal: 15,
    caffeineMg: 150,
    allergens: [],
    tags: ['vegan', 'no-added-sugar', 'decaf-available'],
    price: 100,
    customizations: BLACK_ICED,
    defaultShots: 2,
    image: img('espresso-tonic'),
    art: { tone: '#DCE3EC', ink: '#3A2418' },
    pairsWith: 'egg-white-spinach-omelette',
  }),
  iced({
    slug: 'iced-flat-white',
    name: { en: 'Iced Flat White', ar: 'آيس فلات وايت' },
    description: {
      en: 'Two ristretto shots over cold whole milk and ice.',
      ar: 'شوتان ريستريتو على حليب كامل الدسم بارد وثلج.',
    },
    kcal: 110,
    caffeineMg: 130,
    allergens: ['milk'],
    tags: ['dairy-free-option', 'decaf-available', 'no-added-sugar'],
    price: 125,
    customizations: ICED,
    defaultShots: 2,
    image: img('iced-latte'),
    art: { tone: '#D8E6E3', ink: '#8B6245' },
    pairsWith: 'greek-yogurt-berry-parfait',
  }),
  iced({
    slug: 'iced-saffron-honey-latte',
    name: { en: 'Iced Saffron Honey Latte', ar: 'آيس لاتيه الزعفران والعسل' },
    description: {
      en: 'Our seasonal saffron and Sidr honey latte, poured over ice.',
      ar: 'لاتيه الزعفران وعسل السدر الموسمي، على الثلج.',
    },
    kcal: 200,
    caffeineMg: 150,
    allergens: ['milk'],
    tags: ['seasonal', 'dairy-free-option'],
    price: 160,
    customizations: ICED,
    defaultShots: 2,
    image: img('iced-coffee-bar'),
    art: { tone: '#F3E6CF', ink: '#B07A34' },
    pairsWith: 'overnight-oats-dates-tahini',
  }),
  iced({
    slug: 'salted-caramel-cold-brew',
    name: { en: 'Salted Caramel Cold Brew', ar: 'كولد برو بالكراميل المملح' },
    description: {
      en: '18-hour cold brew with salted caramel and a float of cold foam.',
      ar: 'كولد برو ١٨ ساعة بالكراميل المملح وطبقة رغوة باردة.',
    },
    kcal: 180,
    caffeineMg: 200,
    allergens: ['milk'],
    tags: [],
    price: 145,
    customizations: ['size', 'sweetness', 'ice'],
    image: img('iced-coffee-cream'),
    art: { tone: '#EBD9DC', ink: '#3A2418' },
    pairsWith: 'avocado-egg-sourdough',
  }),
  iced({
    slug: 'iced-mocha',
    name: { en: 'Iced Mocha', ar: 'آيس موكا' },
    description: {
      en: 'Espresso, dark chocolate and cold milk over ice.',
      ar: 'إسبريسو وشوكولاتة داكنة وحليب بارد على الثلج.',
    },
    kcal: 290,
    caffeineMg: 155,
    allergens: ['milk', 'soy'],
    tags: ['dairy-free-option', 'decaf-available'],
    price: 150,
    customizations: ICED,
    defaultShots: 2,
    image: img('iced-latte'),
    art: { tone: '#E6EEDC', ink: '#4A2A1C' },
    pairsWith: 'greek-yogurt-berry-parfait',
  }),
];

type BeanInput = {
  slug: string;
  name: MenuItem['name'];
  price: number;
  bean: BeanDetails;
  description: MenuItem['description'];
  tags?: MenuItem['tags'];
};

const beanTone: Record<keyof typeof originColors, string> = {
  ethiopia: '#F3E6CF',
  colombia: '#F2DDD4',
  brazil: '#DCE5DA',
  kenya: '#EBD9DC',
  guatemala: '#EFE3D2',
  sumatra: '#DEDDE3',
  house: '#D8E6E3',
  turkish: '#E7E1D6',
};

const beans = ({ slug, name, price, bean, description, tags = [] }: BeanInput): MenuItem => ({
  id: slug,
  slug,
  category: 'coffee-beans',
  kind: 'beans',
  name,
  description,
  kcal: 0,
  allergens: [],
  tags: ['vegan', ...tags],
  basePrice: priceTable(price),
  customizable: true,
  customizations: [],
  image: img('coffee-beans-closeup'),
  art: { tone: beanTone[bean.origin], ink: originColors[bean.origin] },
  bean,
});

const n = (en: string, ar: string) => ({ en, ar });

export const coffeeBeans: MenuItem[] = [
  beans({
    slug: 'ethiopia-yirgacheffe',
    name: n('Ethiopia Yirgacheffe', 'إثيوبيا يرجاتشيفي'),
    description: n(
      'Washed heirloom coffee from the Gedeo Zone. Floral, bright and tea-like.',
      'بن إثيوبي مغسول من منطقة جيديو. زهري ومنعش كالشاي.',
    ),
    price: 520,
    bean: {
      origin: 'ethiopia',
      label: 'ETHIOPIA',
      region: n('Gedeo Zone', 'منطقة جيديو'),
      altitude: '1,900–2,200 M',
      process: n('Washed', 'مغسول'),
      varietal: n('Ethiopian heirloom', 'أصناف إثيوبية محلية'),
      roast: 'light',
      roastLevel: 1,
      notes: [n('Jasmine', 'ياسمين'), n('Bergamot', 'برغموت'), n('White peach', 'خوخ أبيض')],
      story: n(
        'Grown by smallholders around Yirgacheffe town and washed at a community station, where cherries are sorted by hand before fermenting for 36 hours.',
        'يزرعه صغار المزارعين حول مدينة يرجاتشيفي ويُغسل في محطة مجتمعية، حيث تُفرز الثمار يدويًا قبل تخميرها ٣٦ ساعة.',
      ),
    },
  }),
  beans({
    slug: 'colombia-huila',
    name: n('Colombia Huila', 'كولومبيا هويلا'),
    description: n(
      'A sweet, balanced washed Colombian for every brewer.',
      'بن كولومبي مغسول، حلو ومتوازن لكل طرق التحضير.',
    ),
    price: 480,
    bean: {
      origin: 'colombia',
      label: 'COLOMBIA',
      region: n('Huila', 'هويلا'),
      altitude: '1,500–1,900 M',
      process: n('Washed', 'مغسول'),
      varietal: n('Caturra, Castillo', 'كاتورا، كاستيو'),
      roast: 'medium',
      roastLevel: 3,
      notes: [n('Red apple', 'تفاح أحمر'), n('Panela', 'بانيلا'), n('Cocoa', 'كاكاو')],
      story: n(
        'Sourced from family farms on the slopes of the Andes in southern Huila, dried slowly on raised parabolic beds.',
        'من مزارع عائلية على سفوح الأنديز جنوب هويلا، ويُجفف ببطء على أسرّة مرتفعة.',
      ),
    },
  }),
  beans({
    slug: 'brazil-cerrado-mineiro',
    name: n('Brazil Cerrado Mineiro', 'البرازيل سيرادو مينيرو'),
    description: n(
      'Nutty, chocolatey natural Brazil. Great with milk.',
      'بن برازيلي طبيعي بطعم البندق والشوكولاتة. رائع مع الحليب.',
    ),
    price: 450,
    bean: {
      origin: 'brazil',
      label: 'BRAZIL',
      region: n('Minas Gerais', 'ميناس جيرايس'),
      altitude: '900–1,250 M',
      process: n('Natural', 'طبيعي'),
      varietal: n('Yellow Bourbon, Catuaí', 'بوربون أصفر، كاتواي'),
      roast: 'medium-dark',
      roastLevel: 4,
      notes: [n('Hazelnut', 'بندق'), n('Milk chocolate', 'شوكولاتة بالحليب'), n('Brown sugar', 'سكر بني')],
      story: n(
        'From the Cerrado Mineiro plateau, the first Brazilian region with a protected designation of origin for coffee.',
        'من هضبة سيرادو مينيرو، أول منطقة برازيلية تحصل على تسمية منشأ محمية للبن.',
      ),
    },
  }),
  beans({
    slug: 'kenya-nyeri-aa',
    name: n('Kenya Nyeri AA', 'كينيا نييري AA'),
    description: n(
      'Juicy, vivid Kenyan with big fruit acidity.',
      'بن كيني غني بالعصارة وحموضة الفاكهة.',
    ),
    price: 560,
    bean: {
      origin: 'kenya',
      label: 'KENYA',
      region: n('Nyeri', 'نييري'),
      altitude: '1,700–1,900 M',
      process: n('Washed', 'مغسول'),
      varietal: n('SL28, SL34', 'SL28، SL34'),
      roast: 'light-medium',
      roastLevel: 2,
      notes: [n('Blackcurrant', 'كشمش أسود'), n('Grapefruit', 'جريب فروت'), n('Hibiscus', 'كركديه')],
      story: n(
        'AA is the largest screen size in Kenya’s grading system. This lot comes from a cooperative factory on the foothills of Mount Kenya.',
        'درجة AA هي أكبر حجم حبة في نظام التصنيف الكيني. تأتي هذه الدفعة من تعاونية على سفوح جبل كينيا.',
      ),
    },
  }),
  beans({
    slug: 'guatemala-antigua',
    name: n('Guatemala Antigua', 'جواتيمالا أنتيجوا'),
    description: n(
      'Rich chocolate and spice from volcanic soil.',
      'شوكولاتة وتوابل غنية من تربة بركانية.',
    ),
    price: 490,
    bean: {
      origin: 'guatemala',
      label: 'GUATEMALA',
      region: n('Antigua', 'أنتيجوا'),
      altitude: '1,500–1,700 M',
      process: n('Washed', 'مغسول'),
      varietal: n('Bourbon, Caturra', 'بوربون، كاتورا'),
      roast: 'medium',
      roastLevel: 3,
      notes: [n('Dark chocolate', 'شوكولاتة داكنة'), n('Orange zest', 'قشر برتقال'), n('Spice', 'توابل')],
      story: n(
        'Grown in the valley between three volcanoes, where mineral-rich soil and cool nights slow the cherries’ ripening.',
        'يُزرع في وادٍ بين ثلاثة براكين، حيث تبطئ التربة الغنية والليالي الباردة نضج الثمار.',
      ),
    },
  }),
  beans({
    slug: 'sumatra-mandheling',
    name: n('Sumatra Mandheling', 'سومطرة ماندهيلنج'),
    description: n(
      'Heavy-bodied and earthy, with a long cocoa finish.',
      'قوام ثقيل وطابع ترابي مع نهاية كاكاو طويلة.',
    ),
    price: 470,
    bean: {
      origin: 'sumatra',
      label: 'SUMATRA',
      region: n('North Sumatra', 'شمال سومطرة'),
      altitude: '1,100–1,500 M',
      process: n('Wet-hulled', 'مقشور رطب'),
      varietal: n('Typica, Ateng', 'تيبيكا، أتينج'),
      roast: 'dark',
      roastLevel: 5,
      notes: [n('Cedar', 'أرز'), n('Dark cocoa', 'كاكاو داكن'), n('Earthy', 'ترابي')],
      story: n(
        'Wet-hulling — giling basah — is unique to Indonesia and gives Mandheling its syrupy body and deep, savoury notes.',
        'التقشير الرطب طريقة إندونيسية فريدة تمنح ماندهيلنج قوامه الكثيف ونكهته العميقة.',
      ),
    },
  }),
  beans({
    slug: 'mazaq-house-espresso',
    name: n('Mazaq House Espresso', 'إسبريسو مذاق هاوس'),
    description: n(
      'The blend behind every Mazaq drink. Sweet in milk, balanced on its own.',
      'الخلطة وراء كل مشروب في مذاق. حلوة مع الحليب ومتوازنة وحدها.',
    ),
    price: 430,
    tags: ['bestseller'],
    bean: {
      origin: 'house',
      label: 'HOUSE',
      region: n('Brazil · Colombia · Ethiopia', 'البرازيل · كولومبيا · إثيوبيا'),
      altitude: '900–2,200 M',
      process: n('Natural + washed', 'طبيعي + مغسول'),
      varietal: n('Blend', 'خلطة'),
      roast: 'medium-dark',
      roastLevel: 4,
      notes: [n('Caramel', 'كراميل'), n('Cocoa', 'كاكاو'), n('Red fruit', 'فاكهة حمراء')],
      blend: true,
      story: n(
        'Brazil for body, Colombia for sweetness and a little Ethiopia for lift. Rebalanced every season as new crops arrive.',
        'البرازيل للقوام، وكولومبيا للحلاوة، وقليل من إثيوبيا للانتعاش. نعيد ضبطها كل موسم مع وصول المحاصيل الجديدة.',
      ),
    },
  }),
  beans({
    slug: 'mazaq-turkish-blend',
    name: n('Mazaq Turkish Blend', 'بن مذاق التركي'),
    description: n(
      'Extra-fine grind for kanaka and ibrik. Plain or with cardamom.',
      'طحنة ناعمة جدًا للكنكة. سادة أو بالحبهان.',
    ),
    price: 360,
    tags: ['turkish'],
    bean: {
      origin: 'turkish',
      label: 'TURKISH',
      region: n('Brazil · Colombia', 'البرازيل · كولومبيا'),
      altitude: '900–1,900 M',
      process: n('Natural + washed', 'طبيعي + مغسول'),
      varietal: n('Blend, extra-fine grind', 'خلطة، طحنة ناعمة جدًا'),
      roast: 'medium',
      roastLevel: 3,
      notes: [n('Toasted nuts', 'مكسرات محمصة'), n('Cardamom option', 'بالحبهان حسب الطلب')],
      blend: true,
      story: n(
        'Roasted to a medium colour so the coffee stays sweet in the cezve, then ground as fine as flour.',
        'يُحمَّص لدرجة متوسطة ليبقى حلوًا في الكنكة، ثم يُطحن ناعمًا كالدقيق.',
      ),
    },
  }),
];

type FoodInput = Omit<MenuItem, 'id' | 'basePrice' | 'customizable' | 'customizations' | 'category' | 'kind'> & {
  price: number;
};

const breakfast = ({ price, ...f }: FoodInput): MenuItem => ({
  ...f,
  id: f.slug,
  category: 'healthy-breakfast',
  kind: 'food',
  basePrice: priceTable(price),
  customizable: false,
  customizations: [],
});

export const healthyBreakfast: MenuItem[] = [
  breakfast({
    slug: 'avocado-egg-sourdough',
    name: n('Avocado & Egg Sourdough', 'توست ساوردو بالأفوكادو والبيض'),
    description: n('Smashed avocado, soft egg, chilli flakes, dukkah.', 'أفوكادو مهروس، بيضة نصف سوي، شطة مجروشة، دُقة.'),
    kcal: 410,
    proteinG: 18,
    allergens: ['gluten', 'eggs', 'sesame', 'nuts'],
    tags: ['vegetarian', 'high-protein'],
    price: 185,
    image: img('avocado-egg-sourdough'),
    art: { tone: '#E6EEDC', ink: '#3F6B35' },
  }),
  breakfast({
    slug: 'greek-yogurt-berry-parfait',
    name: n('Greek Yogurt Berry Parfait', 'بارفيه الزبادي اليوناني بالتوت'),
    description: n('Strained yogurt, mixed berries, honey granola.', 'زبادي مصفّى، توت مشكّل، جرانولا بالعسل.'),
    kcal: 290,
    proteinG: 17,
    allergens: ['milk', 'gluten', 'nuts'],
    tags: ['vegetarian', 'under-300'],
    price: 140,
    image: img('yogurt-parfait'),
    art: { tone: '#EBD9DC', ink: '#F7F3EC' },
  }),
  breakfast({
    slug: 'overnight-oats-dates-tahini',
    name: n('Overnight Oats, Dates & Tahini', 'شوفان منقوع بالتمر والطحينة'),
    description: n('Oats soaked in oat milk, Medjool dates, tahini drizzle.', 'شوفان منقوع في حليب الشوفان، تمر مجدول، طحينة.'),
    kcal: 350,
    proteinG: 11,
    allergens: ['gluten', 'sesame'],
    tags: ['vegan'],
    price: 130,
    image: img('overnight-oats'),
    art: { tone: '#F3E6CF', ink: '#D8C3A0' },
  }),
  breakfast({
    slug: 'green-shakshuka',
    name: n('Green Shakshuka', 'شكشوكة خضراء'),
    description: n('Two eggs baked in spinach and herbs, feta, whole-wheat pita.', 'بيضتان في السبانخ والأعشاب، جبنة فيتا، عيش بلدي أسمر.'),
    kcal: 380,
    proteinG: 22,
    allergens: ['eggs', 'milk', 'gluten'],
    tags: ['vegetarian', 'high-protein'],
    price: 175,
    image: img('shakshuka'),
    art: { tone: '#DCE5DA', ink: '#6E8B3D' },
  }),
  breakfast({
    slug: 'acai-bowl',
    name: n('Açaí Bowl', 'طبق الأساي'),
    description: n('Açaí, banana, granola, coconut, peanut butter.', 'أساي، موز، جرانولا، جوز هند، زبدة فول سوداني.'),
    kcal: 330,
    proteinG: 8,
    allergens: ['peanuts', 'gluten'],
    tags: ['vegan'],
    price: 170,
    image: img('acai-bowl'),
    art: { tone: '#EBD9DC', ink: '#6B2A3A' },
  }),
  breakfast({
    slug: 'halloumi-zaatar-wrap',
    name: n("Halloumi & Za'atar Wrap", 'راب حلوم بالزعتر'),
    description: n(
      "Whole-wheat wrap, grilled halloumi, tomato, cucumber, za'atar.",
      'راب قمح كامل، حلوم مشوي، طماطم، خيار، زعتر.',
    ),
    kcal: 420,
    proteinG: 21,
    allergens: ['milk', 'gluten', 'sesame'],
    tags: ['vegetarian', 'high-protein'],
    price: 165,
    // No free Unsplash photo of a halloumi wrap was found — illustrated art until the client shoots one.
    image: null,
    art: { tone: '#F3E6CF', ink: '#C98F52' },
  }),
  breakfast({
    slug: 'egg-white-spinach-omelette',
    name: n('Egg-White & Spinach Omelette', 'أومليت بياض البيض بالسبانخ'),
    description: n('Egg whites, spinach, mushrooms, side salad.', 'بياض بيض، سبانخ، مشروم، سلطة جانبية.'),
    kcal: 240,
    proteinG: 24,
    allergens: ['eggs'],
    tags: ['gluten-free', 'high-protein', 'under-300'],
    price: 150,
    image: img('omelette'),
    art: { tone: '#E6EEDC', ink: '#6E8B3D' },
  }),
];

const bake = ({ price, ...f }: FoodInput): MenuItem => ({
  ...f,
  id: f.slug,
  category: 'bakes',
  kind: 'bake',
  basePrice: priceTable(price),
  customizable: false,
  customizations: [],
  placeholder: true,
});

/** PLACEHOLDER bakes — the brief lists a Bakes category without items. */
export const bakes: MenuItem[] = [
  bake({
    slug: 'butter-croissant',
    name: n('Butter Croissant', 'كرواسون بالزبدة'),
    description: n('Laminated with cultured butter, baked every morning.', 'مورّق بالزبدة ويُخبز كل صباح.'),
    kcal: 290,
    proteinG: 6,
    allergens: ['gluten', 'milk', 'eggs'],
    tags: ['vegetarian'],
    price: 65,
    image: img('croissants'),
    art: { tone: '#F3E6CF', ink: '#C98F52' },
  }),
  bake({
    slug: 'zaatar-cheese-croissant',
    name: n("Za'atar & Cheese Croissant", 'كرواسون بالزعتر والجبنة'),
    description: n("Butter croissant filled with white cheese and za'atar.", 'كرواسون بالزبدة محشو بالجبنة البيضاء والزعتر.'),
    kcal: 340,
    proteinG: 11,
    allergens: ['gluten', 'milk', 'eggs', 'sesame'],
    tags: ['vegetarian'],
    price: 80,
    image: img('croissant-tray'),
    art: { tone: '#F3E6CF', ink: '#8A5A2B' },
  }),
  bake({
    slug: 'cardamom-morning-bun',
    name: n('Cardamom Morning Bun', 'مورنينج بن بالحبهان'),
    description: n('Swirled croissant dough, cardamom sugar, orange zest.', 'عجينة كرواسون ملفوفة بسكر الحبهان وقشر البرتقال.'),
    kcal: 360,
    proteinG: 6,
    allergens: ['gluten', 'milk', 'eggs'],
    tags: ['vegetarian'],
    price: 85,
    image: img('pastries-latte'),
    art: { tone: '#F3E6CF', ink: '#B07A34' },
  }),
];

export const menuItems: MenuItem[] = [
  ...hotCoffee,
  ...icedCoffee,
  ...coffeeBeans,
  ...healthyBreakfast,
  ...bakes,
];
